# Generated by Django 5.1 on 2024-12-20 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='nombre',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='finalAPP.institucion'),
        ),
    ]
